from crewai import Agent, Task, Crew,LLM
import pandas as pd
from faker import Faker
import json
from typing import Dict, List
import numpy as np
import os ,re

os.environ["HUGGINGFACEHUB_API_TOKEN"]="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"
os.environ['GROQ_API_KEY'] = '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'
llm = LLM(
    model="groq/llama3-70b-8192",
    temperature=0.15,
    base_url="https://api.groq.com/openai/v1",
    api_key=os.environ['GROQ_API_KEY']
)

# Initialize Faker
fake = Faker()

# New Data Analysis Agent
data_analyzer_agent = Agent(
    role='Data Analysis Expert',
    goal='Analyze input dataset and extract metadata for synthetic data generation',
    backstory='''You are an expert data analyst who can analyze datasets and
    extract key patterns, distributions, and relationships between fields. You provide
    detailed metadata that can be used for synthetic data generation.''',
    llm=llm,
    verbose=True
)

# Existing Agents
planner_agent = Agent(
    role='Data Planning Expert',
    goal='Create detailed plans for synthetic data generation based on input metadata',
    backstory='''You are an expert in data analysis and planning. Your job is to
    analyze metadata and create detailed plans for synthetic data generation.''',
    llm=llm,
    verbose=True
)

generator_agent = Agent(
    role='Data Generation Expert',
    goal='Generate synthetic data according to the specified plan using Python and Faker library',
    backstory='''You are an expert in data generation using Python and Faker.
    You create high-quality synthetic data that matches required specifications.
    You always return valid Python code as a string that generates a pandas DataFrame.
    check for valid datatypes, ranges, and relationships between fields.''',
    llm=llm,
    verbose=True
)

semantic_validator = Agent(
    
    role='Semantic Validation Expert',
    goal='Ensure semantic correctness of generated data',
    backstory='''You are specialized in validating data semantics and ensuring
    data makes logical sense within its domain.''',
    llm=llm,
    verbose=True
)

numerical_validator = Agent(
    role='Numerical Validation Expert',
    goal='Verify numerical properties and ranges of generated data',
    backstory='''You are an expert in statistical analysis and numerical validation,
    ensuring data meets specified numerical constraints.''',
    llm=llm,
    verbose=True
)

logical_validator = Agent(
    role='Logical Validation Expert',
    goal='Verify logical relationships and constraints in the data',
    backstory='''You are specialized in checking logical consistency and relationships
    between different data fields.''',
    llm=llm,
    verbose=True
)

# New Dataset Comparison Agent
data_comparison_agent = Agent(
    role='Dataset Comparison Expert',
    goal='Compare original and synthetic datasets for similarity and quality',
    backstory='''You are an expert in statistical comparison of datasets. You analyze
    distributions, relationships, and patterns to ensure synthetic data closely matches
    the original dataset while maintaining privacy.''',
    llm=llm,
    verbose=True
)

class DataGenerationPipeline:
    def __init__(self, input_data: pd.DataFrame, max_retries: int = 3):
        self.input_data = input_data
        self.faker = Faker()
        self.max_retries = max_retries

    def create_semantic_validation_task(self, generation_code: str, metadata: str) -> Task:
        return Task(
            description=f'''Validate the semantic correctness of data that would be generated by this code:

            Generation Code:
            {generation_code}

            Original Metadata:
            {metadata}

            Required:
            1. Check if generated values make sense in their business context
            2. Verify categorical values are appropriate
            3. Ensure datetime sequences are logically valid
            4. Check for semantic anomalies
            
            Return a JSON string with:
            {{"valid": boolean, "issues": [list of issues], "suggestions": [list of suggestions]}}''',
            expected_output='''```json
            {
                "valid": true/false,
                "issues": [
                    "Description of semantic issue 1",
                    "Description of semantic issue 2",
                    ...
                ],
                "suggestions": [
                    "Suggestion to fix semantic issue 1",
                    "Suggestion to fix semantic issue 2",
                    ...
                ],
                "field_validations": {
                    "field_name": {
                        "valid": true/false,
                        "issues": ["issue1", "issue2"],
                        "context": "business context explanation"
                    }
                }
            }```''',
            agent=semantic_validator
        )

    def create_numerical_validation_task(self, generation_code: str, metadata: str) -> Task:
        return Task(
            description=f'''Validate the numerical properties of data that would be generated by this code:

            Generation Code:
            {generation_code}

            Original Metadata:
            {metadata}

            Required:
            1. Verify numerical ranges are within expected bounds
            2. Check statistical distributions
            3. Validate mathematical relationships
            4. Ensure proper handling of special cases (zero, negative values, etc.)
            
            Return a JSON string with:
            {{"valid": boolean, "issues": [list of issues], "suggestions": [list of suggestions]}}''',
            expected_output='''A JSON string containing:
            {
                "valid": true/false,
                "issues": [
                    "Description of numerical issue 1",
                    "Description of numerical issue 2",
                    ...
                ],
                "suggestions": [
                    "Suggestion to fix numerical issue 1",
                    "Suggestion to fix numerical issue 2",
                    ...
                ],
                "numerical_validations": {
                    "field_name": {
                        "valid": true/false,
                        "range_check": {
                            "min": "value",
                            "max": "value",
                            "within_bounds": true/false
                        },
                        "distribution_check": {
                            "expected_distribution": "description",
                            "actual_distribution": "description",
                            "valid": true/false
                        },
                        "special_cases_handled": true/false
                    }
                }
            }''',
            agent=numerical_validator
        )

    def create_logical_validation_task(self, generation_code: str, metadata: str) -> Task:
        return Task(
            description=f'''Validate the logical relationships in data that would be generated by this code:

            Generation Code:
            {generation_code}

            Original Metadata:
            {metadata}

            Required:
            1. Verify relationships between fields are maintained
            2. Check temporal consistency
            3. Validate business rules and constraints
            4. Ensure referential integrity
            
            Return a JSON string with:
            {{"valid": boolean, "issues": [list of issues], "suggestions": [list of suggestions]}}''',
            expected_output='''A JSON string containing:
            {
                "valid": true/false,
                "issues": [
                    "Description of logical issue 1",
                    "Description of logical issue 2",
                    ...
                ],
                "suggestions": [
                    "Suggestion to fix logical issue 1",
                    "Suggestion to fix logical issue 2",
                    ...
                ],
                "relationship_validations": {
                    "relationship_name": {
                        "fields_involved": ["field1", "field2"],
                        "valid": true/false,
                        "issues": ["issue1", "issue2"],
                        "constraint_type": "description of constraint"
                    },
                    "temporal_validations": {
                        "valid": true/false,
                        "sequence_checks": [
                            {
                                "fields": ["date1", "date2"],
                                "valid": true/false,
                                "issue": "description if invalid"
                            }
                        ]
                    },
                    "referential_integrity": {
                        "valid": true/false,
                        "violations": ["description of violation 1", "description of violation 2"]
                    }
                }
            }''',
            agent=logical_validator
        )

    def create_analysis_task(self) -> Task:
        return Task(
            description=f'''Analyze the following dataset and extract metadata for synthetic generation:

            Dataset Sample:
            {self.input_data.head().to_string()}

            Dataset Statistics:
            {self.input_data.describe().to_string()}

            consider the current input dataset as 1st quartile data and according to that make ranges and distribution of synthetic data 
            dont decide the min amd max range according to the input dataset rather conside it be the first qurtile and make accordingly the range 
            and please keep in mind if parameter like age and other then it should be whole number not a float
            Required:
            1. Analyze data types, ranges, and distributions
            2. Identify relationships between fields
            3. Extract categorical values and their frequencies
            4. Return as a JSON string containing metadata
            
            ''',
            expected_output='''A JSON string containing the dataset metadata with:
            1. Field types and constraints
            2. Value ranges and distributions
            3. Relationships between fields
            4. Categorical values and frequencies''',
            agent=data_analyzer_agent
        )

    def create_planning_task(self, metadata: str) -> Task:
        return Task(
            description=f'''Create a detailed plan for synthetic data generation using this metadata:
            {metadata}
            consider the current input dataset as 1st quartile data and according to that make ranges and distribution of synthetic data 
            dont decide the min amd max range according to the input dataset rather conside it ti be the first qurtile and make accordingly the range 
            and please keep in mind if parameter like age and other then it should be whole number not a float
            Return the plan as a JSON string.''',
            expected_output='''A JSON string containing the detailed plan with:
            1. Data types for each field
            2. Generation rules and constraints
            3. Inter-field relationships
            4. Validation criteria''',
            agent=planner_agent
        )

    def create_generation_task(self, plan: str) -> Task:
        return Task(
            description=f'''Generate Python code that creates synthetic data according to this plan: {plan}

            Important:
            1. Return ONLY the Python code as a string, no explanations
            2. The code should use pandas and faker to generate a DataFrame named 'generated_data' use faker only for categorical values
            3. Include all necessary imports in the code
            4. The code should be complete and runnable
            5. only give me the pandas code 
            6. make minimumun 200 rows of data
            7. code should be correct and upto date

            Example format:
            import pandas as pd
            from faker import Faker
            fake = Faker()
            # ... rest of the code ...
            generated_data = pd.DataFrame(data)
            print(generated_data.head())
            ''',
            expected_output='''A string containing complete Python code that generates a pandas DataFrame''',
            agent=generator_agent
        )

    def create_comparison_task(self, generation_code: str) -> Task:
        return Task(
            description=f'''Compare the original dataset with the synthetic dataset that would be generated by this code:

            Original Dataset Sample:
            {self.input_data.head().to_string()}

            Generation Code:
            {generation_code}

            Required:
            1. Analyze statistical similarity
            2. Check distribution preservation
            3. Verify relationship preservation
            4. Return a detailed comparison report as JSON
            ''',
            expected_output='''A JSON string containing comparison metrics and analysis''',
            agent=data_comparison_agent
        )

    def execute_pipeline(self) -> Dict:
        try:
            # Step 1: Initial Analysis
            analysis_crew = Crew(
                agents=[data_analyzer_agent],
                tasks=[self.create_analysis_task()],
                verbose=True
            )
            metadata = analysis_crew.kickoff()

            for attempt in range(self.max_retries):
                print(f"\nAttempt {attempt + 1} of {self.max_retries}")

                # Step 2: Planning
                planning_crew = Crew(
                    agents=[planner_agent],
                    tasks=[self.create_planning_task(metadata)],
                    verbose=True
                )
                plan = planning_crew.kickoff()

                # Step 3: Generation
                generation_crew = Crew(
                    agents=[generator_agent],
                    tasks=[self.create_generation_task(plan)],
                    verbose=True
                )
                generation_code = generation_crew.kickoff()

                # Step 4: Validation
                validation_crews = [
                    Crew(
                        agents=[semantic_validator],
                        tasks=[self.create_semantic_validation_task(generation_code, metadata)],
                        verbose=True,
                        process_delegation=True
                    ),
                    Crew(
                        agents=[numerical_validator],
                        tasks=[self.create_numerical_validation_task(generation_code, metadata)],
                        verbose=True,
                        process_delegation=True
                    ),
                    Crew(
                        agents=[logical_validator],
                        tasks=[self.create_logical_validation_task(generation_code, metadata)],
                        verbose=True,
                        process_delegation=True
                    )
                ]

                validation_results = []
                for crew in validation_crews:
                    result=crew.kickoff()
                    result=re.search(r"```(?:json)?\n(.*?)```", str(result.raw), re.DOTALL | re.IGNORECASE)
                    if result:
                      code = result.group(1).strip()
                      print(code)
                      result1 = json.loads(code)
                      validation_results.append(result1)
    

                # Check if all validations passed
                all_valid = all(result.get('valid', False) for result in validation_results)
                
                if all_valid:
                    # Step 5: Final Comparison
                    comparison_crew = Crew(
                        agents=[data_comparison_agent],
                        tasks=[self.create_comparison_task(generation_code)],
                        verbose=True
                    )
                    comparison_result = comparison_crew.kickoff()

                    return {
                        'metadata': metadata,
                        'plan': plan,
                        'generation_code': generation_code,
                        'validation_results': validation_results,
                        'comparison': comparison_result
                    }
                else:
                    print("\nValidation failed. Collecting feedback for regeneration...")
                    all_issues = []
                    all_suggestions = []
                    for result in validation_results:
                        all_issues.extend(result.get('issues', []))
                        all_suggestions.extend(result.get('suggestions', []))
                    
                    # Update metadata with validation feedback
                    metadata_dict = json.loads(metadata)
                    metadata_dict['validation_feedback'] = {
                        'issues': all_issues,
                        'suggestions': all_suggestions
                    }
                    metadata = json.dumps(metadata_dict)

            raise Exception("Maximum retry attempts reached without successful validation")

        except Exception as e:
            print(f"\nError details: {str(e)}")
            raise Exception(f"Error in pipeline execution: {str(e)}")

